spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: xoj-backend-user-service
          uri: lb://xoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: xoj-backend-question-service
          uri: lb://xoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: xoj-backend-judge-service
          uri: lb://xoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: xoj-backend-file-service
          uri: lb://xoj-backend-file-service
          predicates:
            - Path=/api/file/**
  application:
    name: xoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: swagger2

# 这个配置是不用看token是否合法 直接通过
gateway:
  excludedUrls: /api/file/v2/api-docs,/api/user/v2/api-docs,/api/user/get/login,/api/user/logout,/user/register,/api/user/update/my,/api/user/login,/user/getLoginUser,/api/user/register,/api/question/list/page/vo,/api/file